name: Build

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npx changelogithub -d
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            FORMAT: dmg
            ASSET_MIME: application/x-apple-diskimage 
          - os: windows-2022
            TARGET: windows
            FORMAT: exe
            ASSET_MIME: application/vnd.microsoft.portable-executable 

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - run: corepack enable

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
